spring.application.name=user-service

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/bidding_user_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=manager

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Z3V4aFJqSmVOUlVJbEZ2QzN3d0h0RkhzRWhWaVppcFVKaFVQMEVYeDliQjN0NQ==
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000